# Generated by Django 3.0.7 on 2020-06-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200625_1312"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="request_ref",
            new_name="callback_url",
        ),
    ]
