# Generated by Django 3.0.7 on 2020-07-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20200630_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="needed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Job",
            ),
        ),
    ]
