# Generated by Django 3.0.7 on 2020-07-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_job_needed_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="output_url",
            new_name="output_bucket",
        ),
    ]
