# Generated by Django 3.0.7 on 2020-08-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200811_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='tag',
            new_name='branch',
        ),
    ]
