# Generated by Django 3.0.7 on 2020-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20200812_1233"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="branch",
        ),
        migrations.AddField(
            model_name="workspace",
            name="branch",
            field=models.CharField(default="master", max_length=200),
            preserve_default=False,
        ),
    ]
