# Generated by Django 3.0.7 on 2020-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20200813_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboutput",
            name="location",
            field=models.CharField(max_length=300),
        ),
    ]
