# Generated by Django 3.0.7 on 2020-08-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200820_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='force_run',
            field=models.BooleanField(default=False),
        ),
    ]
