# Generated by Django 3.0.7 on 2020-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200901_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='action_id',
            field=models.CharField(max_length=200),
        ),
    ]
