# Generated by Django 3.0.7 on 2020-09-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_auto_20200901_0831"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="api.Workspace",
            ),
        ),
    ]
