# Generated by Django 3.2.5 on 2021-09-21 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobserver", "0069_add_created_by_to_org_and_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField()),
                ("email", models.TextField(blank=True)),
                ("telephone", models.TextField(blank=True)),
                ("job_title", models.TextField(blank=True)),
                ("team_name", models.TextField(blank=True)),
                ("organisation", models.TextField(blank=True)),
                ("study_name", models.TextField(blank=True)),
                ("study_purpose", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("author_name", models.TextField(blank=True)),
                ("author_email", models.TextField(blank=True)),
                ("author_organisation", models.TextField(blank=True)),
                ("data_meets_purpose", models.TextField(blank=True)),
                (
                    "need_record_level_data",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=True
                    ),
                ),
                ("record_level_data_reasons", models.TextField(blank=True)),
                ("is_study_research", models.BooleanField(default=False)),
                ("is_study_service_evaluation", models.BooleanField(default=False)),
                ("is_study_audit", models.BooleanField(default=False)),
                ("hra_ires_id", models.TextField(blank=True)),
                ("hra_rec_reference", models.TextField(blank=True)),
                ("institutional_rec_reference", models.TextField(blank=True)),
                ("sponsor_name", models.TextField(blank=True)),
                ("sponsor_email", models.TextField(blank=True)),
                ("sponsor_job_role", models.TextField(blank=True)),
                (
                    "is_on_cmo_priority_list",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "legal_basis_for_accessing_data_under_dpa",
                    models.TextField(blank=True),
                ),
                (
                    "how_is_duty_of_confidentiality_satisfied",
                    models.TextField(blank=True),
                ),
                ("funding_details", models.TextField(blank=True)),
                ("team_details", models.TextField(blank=True)),
                ("previous_experience_with_ehr", models.TextField(blank=True)),
                ("evidence_of_coding", models.TextField(blank=True)),
                (
                    "all_applicants_completed_getting_started",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "evidence_of_sharing_in_public_domain_before",
                    models.TextField(blank=True),
                ),
                (
                    "number_of_researchers_needing_access",
                    models.IntegerField(default=0),
                ),
                ("has_agreed_to_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="jobserver.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearcherRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("job_title", models.TextField()),
                ("email", models.TextField()),
                ("github_username", models.TextField()),
                ("telephone", models.TextField()),
                (
                    "phone_type",
                    models.TextField(
                        choices=[("android", "Android"), ("iphone", "iPhone")]
                    ),
                ),
                ("has_taken_safe_researcher_training", models.BooleanField()),
                ("training_with_org", models.TextField()),
                ("training_passed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_registrations",
                        to="applications.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="researcher_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
