# Generated by Django 3.2.5 on 2021-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_add_application_and_researcher_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="is_study_a_service_evaluation",
        ),
        migrations.AddField(
            model_name="application",
            name="is_study_audit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="is_study_service_evaluation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_study_research",
            field=models.BooleanField(default=False),
        ),
    ]
