# Generated by Django 3.2.5 on 2021-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="has_reached_confirmation",
            field=models.BooleanField(default=False),
        ),
    ]
