# Generated by Django 3.2.5 on 2021-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_add_application_approved_at_and_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.TextField(
                choices=[
                    ("approved_fully", "Approved Fully"),
                    ("approved_subject_to", "Approved Subject To"),
                    ("completed", "Completed"),
                    ("ongoing", "Ongoing"),
                    ("rejected", "Rejected"),
                ],
                default="ongoing",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status_comment",
            field=models.TextField(default=""),
        ),
    ]
