# Generated by Django 4.1.2 on 2023-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_add_commercial_involvement_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyinformationpage",
            name="study_purpose",
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
