# Generated by Django 3.2.5 on 2021-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_auto_20210917_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="study_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="how_is_duty_of_confidentiality_satisfied",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="legal_basis_for_accessing_data_under_dpa",
            field=models.TextField(blank=True),
        ),
    ]
