# Generated by Django 3.2.5 on 2021-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_update_researcher_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="all_applicants_completed_getting_started",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_on_cmo_priority_list",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="need_record_level_data",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], null=True
            ),
        ),
    ]
