# Generated by Django 4.1.2 on 2023-01-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_set_character_limit_on_study_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsordetailspage",
            name="is_member_of_bennett_or_lshtm",
            field=models.BooleanField(default=False),
        ),
    ]
