# Generated by Django 3.2.5 on 2021-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_auto_20210917_1247"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="study_data",
            new_name="data_meets_purpose",
        ),
        migrations.AddField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="need_record_level_data",
            field=models.BooleanField(default=True),
        ),
    ]
