# Generated by Django 4.1.2 on 2023-01-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_add_sponsor_details_page_is_member_of_bennett_or_lshtm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyinformationpage",
            name="study_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studypurposepage",
            name="description",
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
