# Generated by Django 4.1.2 on 2023-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0005_move_max_length_from_study_purpose_to_study_lay_description",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studypurposepage",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
