# Generated by Django 3.2.5 on 2021-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_auto_20210917_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="sponsor_email",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="sponsor_job_role",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="sponsor_name",
            field=models.TextField(blank=True),
        ),
    ]
