# Generated by Django 3.2.5 on 2021-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_split_up_application_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsordetailspage",
            name="institutional_rec_reference",
            field=models.TextField(blank=True),
        ),
    ]
