# Generated by Django 3.2.5 on 2021-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_add_datasets_needed"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcherregistration",
            name="daa",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researcherregistration",
            name="github_username",
            field=models.TextField(blank=True, default=""),
        ),
    ]
