# Generated by Django 4.1.2 on 2023-01-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_remove_max_length_from_lay_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetspage",
            name="needs_ukrr",
            field=models.BooleanField(default=False),
        ),
    ]
