# Generated by Django 3.2.5 on 2021-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_auto_20210917_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="has_agreed_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_on_cmo_priority_list",
            field=models.BooleanField(default=False),
        ),
    ]
