# Generated by Django 3.2.10 on 2021-12-23 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0007_alter_application_status_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deleted_at", None), ("deleted_by", None)),
                    models.Q(
                        models.Q(("deleted_at", None), _negated=True),
                        models.Q(("deleted_by", None), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="applications_application_both_deleted_at_and_deleted_by_set",
            ),
        ),
    ]
