# Generated by Django 3.2.5 on 2021-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_auto_20210917_1324"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="all_applicants_completed_getting_started",
            field=models.BooleanField(default=False),
        ),
    ]
