# Generated by Django 3.2.5 on 2021-09-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_application_all_applicants_completed_getting_started"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="purpose",
        ),
    ]
