# Generated by Django 4.0.6 on 2022-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_add_application_deleted_at_and_deleted_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="application",
            name="applications_application_both_approved_at_and_approved_by_set",
        ),
        migrations.RemoveConstraint(
            model_name="application",
            name="applications_application_both_deleted_at_and_deleted_by_set",
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("approved_at__isnull", True), ("approved_by__isnull", True)
                    ),
                    models.Q(
                        ("approved_at__isnull", False), ("approved_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="applications_application_both_approved_at_and_approved_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("deleted_at__isnull", True), ("deleted_by__isnull", True)
                    ),
                    models.Q(
                        ("deleted_at__isnull", False), ("deleted_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="applications_application_both_deleted_at_and_deleted_by_set",
            ),
        ),
    ]
