# Generated by Django 3.2.5 on 2021-10-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_add_review_and_datetime_fields_to_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="has_reached_confirmation",
        ),
    ]
