# Generated by Django 4.1.2 on 2022-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_set_application_on_delete_protect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.TextField(
                choices=[
                    ("approved_fully", "Approved Fully"),
                    ("approved_subject_to", "Approved Subject To"),
                    ("completed", "Completed"),
                    ("submitted", "Submitted"),
                    ("ongoing", "Ongoing"),
                    ("rejected", "Rejected"),
                    ("deferred", "Deferred"),
                ],
                default="ongoing",
            ),
        ),
    ]
