default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
    - id: format
      name: format
      entry: just format
      language: system
      types: [python]
      require_serial: true
    - id: django-upgrade
      name: django-upgrade
      entry: just django-upgrade
      language: system
      types: [python]
      require_serial: true
    - id: lint
      name: lint
      entry: just lint
      language: system
      types: [python]
      require_serial: true
    - id: hadolint
      name: Hadolint
      description: Haskell-based Docker image linter
      language: docker_image
      types: [dockerfile]
      entry: hadolint/hadolint:v2.14.0@sha256:27086352fd5e1907ea2b934eb1023f217c5ae087992eb59fde121dce9c9ff21e hadolint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key
