{
 "title": "Job Server",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Approved Applications by Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(approved_at, '1w'), COUNT(approved_by_id) as Approvals FROM applications_application\nwhere approved_at is NOT NULL\n GROUP BY time "
    }
   ]
  },
  {
   "title": "Approved Projects",
   "type": "stat",
   "description": "The number of projects with an application",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) FROM jobserver_project where application_url is not NULL"
    }
   ]
  },
  {
   "title": "Projects created by week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(created_at, '1w'), COUNT(id) FROM jobserver_project GROUP BY time \n "
    }
   ]
  },
  {
   "title": "Jobs completed by week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(completed_at, '1w'), COUNT(id) FROM jobserver_job WHERE completed_at is NOT NULL and status='succeeded' GROUP BY time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select date_trunc('month', jr.created_at) as month,\n    count(distinct w.project_id) as active_projects,\n    count(distinct jr.created_by_id) as active_researchers,\n    count(distinct jr.id) as job_requests,\n    count(distinct j.id) as jobs\nfrom jobserver_job as j\n    inner join jobserver_jobrequest as jr on j.job_request_id = jr.id\n    inner join jobserver_workspace as w on jr.workspace_id = w.id\nwhere jr.created_at < date_trunc('month', current_date)\ngroup by month\norder by month desc"
    }
   ]
  },
  {
   "title": "Recent logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(distinct id) FROM jobserver_user where $__timeFilter(last_login) "
    }
   ]
  }
 ]
}