# Generated by Django 4.1.2 on 2022-12-30 10:02

import django.db.models.deletion
import django.utils.timezone
import timeflake.extensions.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobserver", "0004_add_user_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRequest",
            fields=[
                (
                    "id",
                    timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                        error_messages={"invalid": "Invalid timeflake id"},
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("codelist_slug", models.TextField()),
                ("codelist_name", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("commit_sha", models.TextField()),
                (
                    "complete_email_sent_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_request",
                        to="jobserver.jobrequest",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_requests",
                        to="jobserver.project",
                    ),
                ),
            ],
        ),
    ]
