# Generated by Django 4.1.2 on 2023-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="analysisrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="interactive_analysisrequest_both_created_at_and_created_by_set",
            ),
        ),
    ]
