# Generated by Django 4.1.2 on 2023-01-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="complete_email_sent_at",
            field=models.DateTimeField(null=True),
        ),
    ]
