# Generated by Django 4.1.2 on 2023-01-18 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0005_add_report"),
        ("interactive", "0002_make_complete_email_sent_at_to_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_requests",
                to="jobserver.report",
            ),
        ),
    ]
