# Generated by Django 4.1.2 on 2023-02-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0002_add_check_constraints_for_paired_at_by_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="report",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_request",
                to="jobserver.report",
            ),
        ),
    ]
