# Generated by Django 5.1.6 on 2025-03-13 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0002_remove_analysisrequest_created_by_and_more"),
        (
            "redirects",
            "0003_remove_redirect_redirects_redirect_only_one_target_model_set_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisRequest",
        ),
    ]
