# Generated by Django 4.1.2 on 2023-01-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0003_add_analysis_request_report_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisRequest",
        ),
    ]
