# Generated by Django 4.1.6 on 2023-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0003_convert_analysis_request_report_to_one_to_one_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrequest",
            name="codelist_name",
        ),
        migrations.RemoveField(
            model_name="analysisrequest",
            name="codelist_slug",
        ),
        migrations.RemoveField(
            model_name="analysisrequest",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="analysisrequest",
            name="start_date",
        ),
        migrations.AddField(
            model_name="analysisrequest",
            name="template_data",
            field=models.JSONField(default=dict),
        ),
    ]
