# Generated by Django 4.1.7 on 2023-02-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0004_move_analytical_code_template_values_into_json_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrequest",
            name="commit_sha",
        ),
    ]
