# Generated by Django 4.1.7 on 2023-03-10 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactive", "0005_remove_analysis_request_commit_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="analysisrequest",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_requests_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
