# Generated by Django 4.1.2 on 2023-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
