# Generated by Django 4.1.7 on 2023-03-10 11:08

from django.db import migrations
from django.db.models import F


def backfill_updated_fields(apps, schema_editor):
    AnalysisRequest = apps.get_model("interactive", "AnalysisRequest")

    AnalysisRequest.objects.update(
        updated_at=F("created_at"), updated_by=F("created_by")
    )


def empty_updated_fields(apps, schema_editor):
    AnalysisRequest = apps.get_model("interactive", "AnalysisRequest")
    AnalysisRequest.objects.update(updated_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0006_add_analysis_request_updated_fields"),
    ]

    operations = [
        migrations.RunPython(
            backfill_updated_fields,
            reverse_code=empty_updated_fields,
        )
    ]
