# Generated by Django 4.1.2 on 2023-01-20 10:47

from django.db import migrations
from django.db.models import F
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    AnalysisRequest = apps.get_model("interactive", "AnalysisRequest")
    AnalysisRequest.objects.update(slug=slugify(F("title")))


def empty_slugs(apps, schema_editor):
    AnalysisRequest = apps.get_model("interactive", "AnalysisRequest")
    AnalysisRequest.objects.update(slug="")


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0006_add_analysis_request_slug"),
    ]

    operations = [migrations.RunPython(set_slugs, reverse_code=empty_slugs)]
