# Generated by Django 4.1.2 on 2023-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0007_populate_analysis_request_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
