# Generated by Django 4.1.7 on 2023-03-13 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactive", "0007_backfill_analysis_request_updated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_requests_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("updated_at__isnull", False), ("updated_by__isnull", False)
                ),
                name="interactive_analysisrequest_both_updated_at_and_updated_by_set",
            ),
        ),
    ]
