# Generated by Django 4.1.7 on 2023-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0008_ensure_workspace_updated_fields_are_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="purpose",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
