# Generated by Django 4.1.7 on 2023-03-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0009_add_analysis_request_purpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrequest",
            name="complete_email_sent_at",
        ),
    ]
