# Generated by Django 4.1.10 on 2023-07-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(("slug", ""), _negated=True), name="slug_is_not_empty"
            ),
        ),
    ]
