# Generated by Django 3.2.5 on 2021-11-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="level_4_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="backend",
            name="parent_directory",
            field=models.TextField(blank=True, default=""),
        ),
    ]
