# Generated by Django 5.0.8 on 2024-08-19 08:57

from django.db import migrations, transaction
from social_django.models import UserSocialAuth


@transaction.atomic()
def remove_user_github_access_tokens(apps, schema_editor):
    for user in UserSocialAuth.objects.filter(extra_data__has_key="access_token"):
        del user.extra_data["access_token"]
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0001_squashed_2024_06"),
        ("social_django", "0016_alter_usersocialauth_extra_data"),
    ]

    operations = [migrations.RunPython(remove_user_github_access_tokens)]
