# Generated by Django 3.1.2 on 2021-02-09 13:59

from django.db import migrations


def add_backends(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.create(name="databricks", slug="databricks")
    Backend.objects.create(name="EMIS", slug="emis", is_active=True)
    Backend.objects.create(name="expectations", slug="expectations")
    Backend.objects.create(name="Graphnet", slug="graphnet")
    Backend.objects.create(
        name="Test",
        slug="test",
        level_4_url="https://test.opensafely.org",
    )
    Backend.objects.create(
        name="TPP",
        slug="tpp",
        level_4_url="http://localhost:8001",
        parent_directory="/d/Level4Files/workspaces",
        is_active=True,
    )


def remove_backends(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_backends, reverse_code=remove_backends)]
