# Generated by Django 5.1.7 on 2025-03-28 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0001_squashed_2025_03"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="application_url",
        ),
    ]
