# Generated by Django 4.1.2 on 2022-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
