# Generated by Django 3.2.5 on 2021-10-15 15:49

from django.db import migrations


def add_datalab(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    Org.objects.create(name="DataLab", slug="datalab")


def remove_datalab(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    Org.objects.filter(slug="datalab").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0002_add_backends"),
    ]

    operations = [migrations.RunPython(add_datalab, reverse_code=remove_datalab)]
