# Generated by Django 5.1.7 on 2025-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0002_populate_missing_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.TextField(),
        ),
    ]
