# Generated by Django 4.1.2 on 2022-12-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0002_make_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="application_url",
            field=models.TextField(default=""),
        ),
    ]
