# Generated by Django 3.0.7 on 2020-10-07 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0003_add_custom_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_action", models.TextField()),
                (
                    "backend",
                    models.TextField(
                        choices=[("emis", "EMIS"), ("tpp", "TPP")],
                        db_index=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_requests",
                        to="jobserver.Workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="jobserver.JobRequest",
            ),
        ),
    ]
