# Generated by Django 4.0.1 on 2022-01-28 09:01

import django.contrib.postgres.fields
from django.db import migrations, models

import jobserver.models.core


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0003_alter_backend_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="github_orgs2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                default=jobserver.models.core.default_github_orgs,
                size=None,
            ),
        ),
    ]
