# Generated by Django 5.0.8 on 2024-08-20 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0001_squashed_2024_06"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgmembership",
            name="roles",
        ),
    ]
