# Generated by Django 3.2.5 on 2021-10-21 09:17
from functools import partial

from django.db import migrations


def sql(table_name, *, new_type, needs_cast):
    """Generate SQL to alter roles column types"""
    query = f"""
    ALTER TABLE jobserver_{table_name}
    ALTER COLUMN roles TYPE {new_type}
    """

    if needs_cast:
        query = query + " USING roles::jsonb"

    return query


forward = partial(sql, new_type="jsonb", needs_cast=True)
forwards = [
    (forward("orgmembership"), None),
    (forward("projectinvitation"), None),
    (forward("projectmembership"), None),
    (forward("user"), None),
]


backward = partial(sql, new_type="text", needs_cast=False)
backwards = [
    (backward("orgmembership"), None),
    (backward("projectinvitation"), None),
    (backward("projectmembership"), None),
    (backward("user"), None),
]


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0003_add_datalab_org"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards,
            reverse_sql=backwards,
        )
    ]
