# Generated by Django 5.1.7 on 2025-04-03 16:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0003_populate_missing_fullname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("fullname"),
                    django.db.models.functions.text.Lower("username"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("fullname", ""), _negated=True),
                name="fullname_non_blank",
            ),
        ),
    ]
