# Generated by Django 3.1.2 on 2021-02-09 11:54

from django.db import migrations


class Migration(migrations.Migration):
    """
    No-op migration

    With the removal of the Django Admin we no longer have a django_admin_log
    table against which to run the SQL queries originally in this migration.
    However, we also don't need to fix said table so this migration is now a
    no-op.
    """

    dependencies = [
        ("jobserver", "0003_add_membership_org_and_project"),
    ]

    operations = []
