# Generated by Django 4.1.10 on 2023-07-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0003_create_redirects_to_remove_org_from_all_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(("name__regex", "^[-a-zA-Z0-9_]+\\Z")),
                name="name_is_valid",
            ),
        ),
    ]
