# Generated by Django 5.1.11 on 2025-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0004_make_fullname_nonblank"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="jobrunner_rap_api_state",
            field=models.JSONField(null=True),
        ),
    ]
