# Generated by Django 4.0.1 on 2022-01-28 09:02

from django.db import migrations


def copy_github_orgs(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    for org in Org.objects.all():
        org.github_orgs2 = org.github_orgs
        org.save()


def empty_github_orgs2(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")
    Org.objects.update(github_orgs2=[])


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0004_add_github_orgs2"),
    ]

    operations = [
        migrations.RunPython(
            copy_github_orgs,
            reverse_code=empty_github_orgs2,
        )
    ]
