# Generated by Django 3.0.7 on 2020-10-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0004_add_job_request_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="backend",
        ),
    ]
