# Generated by Django 4.1.10 on 2023-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0004_ensure_workspace_name_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="run_command",
            field=models.TextField(default=""),
        ),
    ]
