# Generated by Django 3.2.5 on 2021-10-28 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0004_fix_roles_column_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="copilot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copiloted_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
