# Generated by Django 4.0.1 on 2022-01-31 10:15

from django.db import migrations


def copy_release_flag_to_workspaces(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    for project in Project.objects.all():
        project.workspaces.update(uses_new_release_flow=project.uses_new_release_flow)


def reset_workspace_release_flag(apps, schema_editor):
    Workspace = apps.get_model("jobserver", "Workspace")

    Workspace.objects.update(uses_new_release_flow=True)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0004_add_workspace_uses_new_release_flow"),
    ]

    operations = [
        migrations.RunPython(
            copy_release_flag_to_workspaces,
            reverse_code=reset_workspace_release_flag,
        )
    ]
