# Generated by Django 3.1.2 on 2021-02-10 11:41

from django.db import migrations
from django.db.models import F


def copy_email_to_notifications_email(apps, schema_editor):
    User = apps.get_model("jobserver", "User")

    User.objects.filter(notifications_email="").update(notifications_email=F("email"))


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0004_fix_django_admin_log_user_constraint"),
    ]

    operations = [
        migrations.RunPython(
            copy_email_to_notifications_email,
            reverse_code=migrations.RunPython.noop,
        )
    ]
