# Generated by Django 5.1.11 on 2025-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0004_make_fullname_nonblank"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="status",
            field=models.TextField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("succeeded", "Succeeded"),
                    ("nothing_to_do", "Nothing To Do"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
            ),
        ),
        migrations.AddField(
            model_name="jobrequest",
            name="status_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
