# Generated by Django 5.1.11 on 2025-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0005_jobrequest_status_jobrequest_status_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="rap_api_state",
            field=models.JSONField(null=True),
        ),
    ]
