# Generated by Django 5.1.12 on 2025-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0005_jobrequest_status_jobrequest_status_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="parent_directory",
        ),
    ]
