# Generated by Django 5.1.1 on 2024-09-13 11:20

from django.db import migrations
from social_django.models import UserSocialAuth


def remove_user_socialauth_token_type(apps, schema_editor):
    users = UserSocialAuth.objects.filter(extra_data__has_key="token_type")
    for user in users:
        del user.extra_data["token_type"]
    UserSocialAuth.objects.bulk_update(users, ["extra_data"])


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0005_remove_user_socialauth_expires"),
        ("social_django", "0016_alter_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.RunPython(
            remove_user_socialauth_token_type, reverse_code=migrations.RunPython.noop
        )
    ]
