# Generated by Django 5.1.11 on 2025-09-10 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0005_backend_jobrunner_rap_api_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backend",
            old_name="jobrunner_rap_api_state",
            new_name="rap_api_state",
        ),
    ]
