# Generated by Django 3.2.5 on 2021-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0005_add_project_copilot"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="copilot_support_ends_at",
            field=models.DateTimeField(
                null=True,
            ),
        ),
    ]
