# Generated by Django 4.0.1 on 2022-01-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0005_copy_github_orgs_to_github_orgs2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="github_orgs",
        ),
    ]
