# Generated by Django 4.0.1 on 2022-01-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0005_copy_project_release_flag_to_workspaces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="uses_new_release_flow",
        ),
    ]
