# Generated by Django 3.1.2 on 2021-02-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0005_copy_email_to_notifications_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="cancelled_actions",
            field=models.JSONField(default=list),
        ),
    ]
