# Generated by Django 4.1.2 on 2023-01-23 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0005_add_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
