# Generated by Django 5.1.12 on 2025-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0006_remove_backend_parent_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="last_seen_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="backend",
            name="last_seen_maintenance_mode",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="backend",
            name="rap_api_state",
            field=models.JSONField(null=True),
        ),
    ]
