# Generated by Django 5.1.12 on 2025-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0006_backend_rap_api_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="last_seen_backend",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="backend",
            name="last_seen_maintenance_mode",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="backend",
            name="maintenance_mode_status",
            field=models.CharField(
                choices=[("on", "On"), ("off", "Off")],
                default="on",
                help_text="Is this backend currently in database maintenance mode?",
                max_length=3,
            ),
        ),
    ]
