# Generated by Django 4.1.2 on 2023-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0006_require_job_request_created_by"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_report_both_created_at_and_created_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("published_at__isnull", True), ("published_by__isnull", True)
                    ),
                    models.Q(
                        ("published_at__isnull", False), ("published_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_report_both_published_at_and_published_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("updated_at__isnull", True), ("updated_by__isnull", True)
                    ),
                    models.Q(
                        ("updated_at__isnull", False), ("updated_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_report_both_updated_at_and_updated_by_set",
            ),
        ),
    ]
