# Generated by Django 3.0.7 on 2020-10-09 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0006_split_force_run_options_between_job_and_job_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
