# Generated by Django 5.1.1 on 2024-09-30 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0006_remove_user_socialauth_token_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
