# Generated by Django 5.1.12 on 2025-10-02 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0007_backend_last_seen_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="level_4_url",
        ),
    ]
