# Generated by Django 5.1.12 on 2025-10-01 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0007_backend_last_seen_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobrequest",
            old_name="status",
            new_name="_status",
        ),
    ]
