# Generated by Django 3.0.7 on 2020-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0006_split_force_run_options_between_job_and_job_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="branch",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
