# Generated by Django 4.2.5 on 2023-09-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0007_add_User_order_by_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="db",
        ),
    ]
