# Generated by Django 3.0.7 on 2020-10-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0007_add_workspace_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="owner",
        ),
    ]
