# Generated by Django 5.1.2 on 2024-10-21 21:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0008_coredeveloper_to_staffareaadministrator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    models.Case(
                        models.When(fullname="", then=1),
                        default=0,
                        output_field=models.IntegerField(),
                    ),
                    django.db.models.functions.text.Lower("fullname"),
                    django.db.models.functions.text.Lower("username"),
                ]
            },
        ),
    ]
