# Generated by Django 3.0.7 on 2020-10-09 15:19

from django.db import migrations


def copy_branches_to_jobrequests(apps, schema_editor):
    JobRequest = apps.get_model("jobserver", "JobRequest")

    for job_request in JobRequest.objects.select_related("workspace"):
        job_request.branch = job_request.workspace.branch
        job_request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0008_add_jobrequest_branch"),
    ]

    operations = [
        migrations.RunPython(
            copy_branches_to_jobrequests, reverse_code=migrations.RunPython.noop
        )
    ]
