# Generated by Django 4.2.6 on 2023-10-13 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0008_remove_workspace_db"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_approved",
        ),
    ]
