# Generated by Django 5.1.12 on 2025-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0008_rename_status_jobrequest__status"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="is_in_maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Is this backend currently in database maintenance mode?",
            ),
        ),
    ]
