# Generated by Django 3.0.7 on 2020-10-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0008_remove_workspace_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="request",
            new_name="job_request",
        ),
    ]
