# Generated by Django 5.1.13 on 2025-10-14 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0009_backend_is_in_maintenance_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="jobrunner_state",
        ),
    ]
