# Generated by Django 3.1.2 on 2021-02-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0009_make_project_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="display_name",
            field=models.TextField(blank=True),
        ),
    ]
