# Generated by Django 4.1.2 on 2023-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0009_add_check_constraints_for_paired_release_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="releasefile",
            name="jobserver_releasefile_deleted_fields_both_set",
        ),
        migrations.AddConstraint(
            model_name="releasefile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_releasefile_both_created_at_and_created_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="releasefile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("deleted_at__isnull", True), ("deleted_by__isnull", True)
                    ),
                    models.Q(
                        ("deleted_at__isnull", False), ("deleted_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_releasefile_both_deleted_at_and_deleted_by_set",
            ),
        ),
    ]
