# Generated by Django 5.1.13 on 2025-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0009_backend_is_in_maintenance_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="level_4_url",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
