# Generated by Django 3.0.7 on 2020-10-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0009_copy_workspace_branch_to_jobrequests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="branch",
        ),
    ]
