# Generated by Django 5.1.2 on 2024-10-21 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0009_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
