# Generated by Django 3.1.2 on 2020-10-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0010_mirror_django_3_1_user_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="requested_actions",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
