# Generated by Django 5.1.6 on 2025-02-24 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0010_remove_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="Summary of the reason for the alert, to display in the title of the alert (optional)",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The message to display in the alert (required)"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("danger", "Danger"),
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                        ],
                        default="warning",
                        help_text="How significant the alert is, for UI styling.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_alerts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_alerts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
