# Generated by Django 3.1.2 on 2021-02-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0010_add_project_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="governance_approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technical_approval_notes",
            field=models.TextField(blank=True),
        ),
    ]
