# Generated by Django 4.0.2 on 2022-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0010_remove_project_uses_new_release_flow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="pat_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pat_token",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("pat_expires_at", None), ("pat_token", None)),
                    models.Q(
                        models.Q(("pat_expires_at", None), _negated=True),
                        models.Q(("pat_token", None), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="jobserver_user_both_pat_expires_at_and_pat_token_set",
            ),
        ),
    ]
