# Generated by Django 5.1.13 on 2025-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0010_remove_backend_jobrunner_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrequest",
            name="_status",
            field=models.TextField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("failed", "Failed"),
                    ("succeeded", "Succeeded"),
                    ("nothing_to_do", "Nothing To Do"),
                    ("unknown", "Unknown"),
                    ("unknown_error_creating_jobs", "Unknown Error Creating Jobs"),
                ],
                default="unknown",
            ),
        ),
    ]
