# Generated by Django 5.1.13 on 2025-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0011_alter_jobrequest__status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="level_4_url",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
