# Generated by Django 4.0.4 on 2022-06-08 15:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0011_add_user_pat_token_and_pat_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="requested_actions2",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
