# Generated by Django 5.1.6 on 2025-03-18 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0011_sitealert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishrequest",
            name="report",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
