# Generated by Django 4.1.2 on 2023-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobserver",
            "0011_add_check_constraints_for_paired_release_file_review_fields",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("internal_signed_off_at__isnull", True),
                        ("internal_signed_off_by__isnull", True),
                    ),
                    models.Q(
                        ("internal_signed_off_at__isnull", False),
                        ("internal_signed_off_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_repo_both_internal_signed_off_at_and_internal_signed_off_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("researcher_signed_off_at__isnull", True),
                        ("researcher_signed_off_by__isnull", True),
                    ),
                    models.Q(
                        ("researcher_signed_off_at__isnull", False),
                        ("researcher_signed_off_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_repo_both_researcher_signed_off_at_and_researcher_signed_off_by_set",
            ),
        ),
    ]
