# Generated by Django 3.1.2 on 2020-10-21 10:40

from django.db import migrations


def convert_requested_action_to_list_of_actions(apps, schema_editor):
    JobRequest = apps.get_model("jobserver", "JobRequest")
    for job_request in JobRequest.objects.all():
        job_request.requested_actions = [job_request.requested_action]
        job_request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0011_add_jobrequest_requested_actions"),
    ]

    operations = [
        migrations.RunPython(
            convert_requested_action_to_list_of_actions,
            reverse_code=migrations.RunPython.noop,
        )
    ]
