# Generated by Django 5.0.1 on 2024-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0011_add_application_approval_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="metrics",
            field=models.JSONField(null=True),
        ),
    ]
