# Generated by Django 3.1.2 on 2021-02-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0011_add_project_approval_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="form_url",
            field=models.TextField(blank=True),
        ),
    ]
