# Generated by Django 3.1.2 on 2020-10-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0012_convert_job_request_requested_action_to_list_of_actions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrequest",
            name="requested_action",
        ),
    ]
