# Generated by Django 4.1.2 on 2023-01-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0012_add_check_constraints_for_paired_repo_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_snapshot_both_created_at_and_created_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshot",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("published_at__isnull", True), ("published_by__isnull", True)
                    ),
                    models.Q(
                        ("published_at__isnull", False), ("published_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_snapshot_both_published_at_and_published_by_set",
            ),
        ),
    ]
