# Generated by Django 4.1.10 on 2023-07-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0012_job_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCollaboration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_lead", models.BooleanField(null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_orgs",
                        to="jobserver.org",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_orgs",
                        to="jobserver.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="orgs",
            field=models.ManyToManyField(
                through="jobserver.ProjectCollaboration",
                to="jobserver.org",
            ),
        ),
    ]
