# Generated by Django 3.1.2 on 2021-02-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0012_add_project_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="next_step",
            field=models.TextField(blank=True),
        ),
    ]
