# Generated by Django 5.1.13 on 2025-10-20 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0012_alter_backend_level_4_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="level_4_url",
        ),
    ]
