# Generated by Django 4.1.2 on 2023-01-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0013_add_check_constraints_for_paired_snapshot_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_workspace_both_created_at_and_created_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("signed_off_at__isnull", True), ("signed_off_by__isnull", True)
                    ),
                    models.Q(
                        ("signed_off_at__isnull", False),
                        ("signed_off_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_workspace_both_signed_off_at_and_signed_off_by_set",
            ),
        ),
    ]
