# Generated by Django 4.1.10 on 2023-07-24 19:33

from django.db import migrations


def copy_project_org_to_orgs(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")
    ProjectCollaboration = apps.get_model("jobserver", "ProjectCollaboration")

    for project in Project.objects.all():
        ProjectCollaboration.objects.create(
            org=project.org,
            project=project,
            is_lead=True,
        )


def delete_project_orgs(apps, schema_editor):
    ProjectCollaboration = apps.get_model("jobserver", "ProjectCollaboration")

    ProjectCollaboration.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0013_add_project_orgs"),
    ]

    operations = [
        migrations.RunPython(
            copy_project_org_to_orgs,
            reverse_code=delete_project_orgs,
            elidable=True,
        )
    ]
