# Generated by Django 5.2.8 on 2025-11-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0013_remove_backend_level_4_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="backends",
            field=models.ManyToManyField(
                related_name="members",
                through="jobserver.BackendMembership",
                through_fields=["user", "backend"],
                to="jobserver.backend",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="orgs",
            field=models.ManyToManyField(
                related_name="members",
                through="jobserver.OrgMembership",
                through_fields=["user", "org"],
                to="jobserver.org",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                related_name="members",
                through="jobserver.ProjectMembership",
                through_fields=["user", "project"],
                to="jobserver.project",
            ),
        ),
    ]
