# Generated by Django 3.1.2 on 2021-03-08 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0013_add_project_next_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("upload_dir", models.TextField()),
                ("files", models.JSONField()),
                ("backend_user", models.TextField()),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="jobserver.backend",
                    ),
                ),
                (
                    "publishing_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="jobserver.workspace",
                    ),
                ),
            ],
        ),
    ]
