# Generated by Django 3.1.2 on 2020-10-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0013_remove_job_request_requested_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["pk"]},
        ),
    ]
