# Generated by Django 4.2.5 on 2023-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0014_copy_project_org_to_orgs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="org",
        ),
        migrations.AlterField(
            model_name="project",
            name="orgs",
            field=models.ManyToManyField(
                related_name="projects",
                to="jobserver.org",
                through="jobserver.ProjectCollaboration",
            ),
        ),
        migrations.AlterField(
            model_name="projectcollaboration",
            name="is_lead",
            field=models.BooleanField(default=False),
        ),
    ]
