# Generated by Django 3.1.2 on 2020-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0014_set_job_ordering_to_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="sha",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
