# Generated by Django 4.1.2 on 2023-02-01 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0014_add_check_constraints_for_paired_workspace_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseFilePublishRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_file_publish_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_file_publish_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        related_name="publish_requests", to="jobserver.releasefile"
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publish_requests",
                        to="jobserver.snapshot",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publish_requests",
                        to="jobserver.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="releasefilepublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("approved_at__isnull", True), ("approved_by__isnull", True)
                    ),
                    models.Q(
                        ("approved_at__isnull", False), ("approved_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_releasefilepublishrequest_both_approved_at_and_approved_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="releasefilepublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_releasefilepublishrequest_both_created_at_and_created_by_set",
            ),
        ),
    ]
