# Generated by Django 5.2.10 on 2026-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0014_alter_user_backends_alter_user_orgs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditableevent",
            name="type",
            field=models.TextField(
                choices=[
                    ("project_member_added", "User added"),
                    ("project_member_removed", "User removed"),
                    ("project_member_updated_roles", "User's roles updated"),
                    ("user_updated_roles", "User's global roles updated"),
                ]
            ),
        ),
    ]
