# Generated by Django 5.2.8 on 2025-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0015_initial_global_user_role_audit_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditableevent",
            name="type",
            field=models.TextField(
                choices=[
                    ("project_member_added", "User added"),
                    ("project_member_removed", "User removed"),
                    ("project_member_updated_roles", "User's roles updated"),
                    ("user_updated_roles", "User's global roles updated"),
                ]
            ),
        ),
    ]
