# Generated by Django 3.1.2 on 2020-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0015_add_jobrequest_sha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_last_seen", models.DateTimeField(null=True)),
            ],
        ),
    ]
