# Generated by Django 3.1.2 on 2021-03-08 14:03

from django.db import migrations


def approve_existing_users(apps, schema_editor):
    User = apps.get_model("jobserver", "User")
    User.objects.update(is_approved=True)


def unapprove_existing_users(apps, schema_editor):
    User = apps.get_model("jobserver", "User")
    User.objects.update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0015_add_user_is_approved"),
    ]
    operations = [
        migrations.RunPython(
            approve_existing_users, reverse_code=unapprove_existing_users
        )
    ]
