# Generated by Django 4.0.4 on 2022-06-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0015_rename_requested_actions2_to_requested_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrequest",
            name="backend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_requests",
                to="jobserver.backend",
            ),
        ),
    ]
