# Generated by Django 5.0.1 on 2024-01-17 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0015_remove_project_org"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectcollaboration",
            unique_together={("org", "project")},
        ),
    ]
