# Generated by Django 4.0.4 on 2022-06-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0016_require_job_request_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("number",),
                name="unique_number_ignore_null",
            ),
        ),
    ]
