# Generated by Django 3.1.2 on 2020-11-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0016_add_stats_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrequest",
            name="force_run",
        ),
    ]
