# Generated by Django 5.2.11 on 2026-02-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0016_alter_auditableevent_type_and_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
