# Generated by Django 5.0.1 on 2024-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobserver",
            "0016_ensure_project_and_org_combinations_are_unique_for_projectcollaborations",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectcollaboration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_lead", True)),
                fields=("project",),
                name="jobserver_projectcollaboration_only_one_lead_org_set",
            ),
        ),
    ]
