# Generated by Django 4.1.2 on 2023-02-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0016_add_report_publish_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="jobserver.project",
            ),
        ),
    ]
