# Generated by Django 5.2.12 on 2026-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0017_alter_project_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("number__isnull", True),
                    ("number__regex", "^[1-9][0-9]*$|^POS-20[0-9]{2}-[1-9][0-9]{3}$"),
                    _connector="OR",
                ),
                name="number_valid_format",
            ),
        ),
    ]
