# Generated by Django 4.0.4 on 2022-06-16 13:49

from django.db import migrations


def move_number_from_title_to_number(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    projects = Project.objects.filter(name__regex=r"^\d{2,3}")
    for project in projects:
        number, _, name = project.name.partition(" ")

        project.name = name
        project.number = number
        project.save()


def move_number_from_number_to_title(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    projects = Project.objects.filter(number__isnull=False)
    for project in projects:
        project.name = f"{project.number} {project.name}"
        project.number = None
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0017_add_project_number"),
    ]

    operations = [
        migrations.RunPython(
            move_number_from_title_to_number,
            reverse_code=move_number_from_number_to_title,
        )
    ]
