# Generated by Django 3.1.2 on 2021-03-11 14:40

from django.db import migrations
from django.utils.text import slugify


def remove_org_slug(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    Org.objects.update(slug="")


def set_org_slug(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    for org in Org.objects.all():
        org.slug = slugify(org.name)
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0017_add_org_slug"),
    ]

    operations = [migrations.RunPython(set_org_slug, reverse_code=remove_org_slug)]
