# Generated by Django 4.1.2 on 2023-02-03 10:38

from django.db import migrations


def add_projects_to_reports(apps, schema_editor):
    Report = apps.get_model("jobserver", "Report")

    for report in Report.objects.all():
        report.project = report.release_file.workspace.project
        report.save()


def remove_projects_from_reports(apps, schema_editor):
    Report = apps.get_model("jobserver", "Report")

    Report.objects.update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0017_add_fk_from_report_to_project"),
    ]

    operations = [
        migrations.RunPython(
            add_projects_to_reports,
            reverse_code=remove_projects_from_reports,
        )
    ]
