# Generated by Django 4.0.4 on 2022-06-23 10:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0018_move_project_numbers_to_number_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="alert_timeout",
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
