# Generated by Django 5.2.12 on 2026-03-12 22:27

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0018_project_number_valid_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[1-9][0-9]*$|^POS-20[0-9]{2}-[1-9][0-9]{3}$")
                    )
                ],
            ),
        ),
    ]
