# Generated by Django 5.0.1 on 2024-01-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0018_switch_project_created_by_to_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("updated_at__isnull", False), ("updated_by__isnull", False)
                ),
                name="jobserver_project_both_updated_at_and_updated_by_set",
            ),
        ),
    ]
