# Generated by Django 3.1.2 on 2020-11-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0018_add_blank_to_nullable_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="callback_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
