# Generated by Django 3.1.2 on 2021-03-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0018_set_org_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="slug",
        ),
    ]
