# Generated by Django 4.1.7 on 2023-03-10 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0019_require_reports_have_a_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
