# Generated by Django 5.2.12 on 2026-03-13 00:09

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0019_alter_project_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(unique=True, verbose_name="Project title"),
        ),
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[1-9][0-9]*$|^POS-20[0-9]{2}-[1-9][0-9]{3}$"),
                        "Enter a whole number or use the format POS-20YY-NNNN (for example, POS-2026-2001).",
                    )
                ],
                verbose_name="Project ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="URL slug"
            ),
        ),
    ]
