# Generated by Django 4.1.7 on 2023-03-10 10:58

from django.db import migrations
from django.db.models import F


def backfill_updated_fields(apps, schema_editor):
    Workspace = apps.get_model("jobserver", "Workspace")

    Workspace.objects.update(updated_at=F("created_at"), updated_by=F("created_by"))


def empty_updated_fields(apps, schema_editor):
    Workspace = apps.get_model("jobserver", "Workspace")
    Workspace.objects.update(updated_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0020_add_workspace_updated_fields"),
    ]

    operations = [
        migrations.RunPython(
            backfill_updated_fields,
            reverse_code=empty_updated_fields,
        )
    ]
