# Generated by Django 3.1.2 on 2020-11-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0020_add_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="selected_workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="jobserver.workspace",
            ),
        ),
    ]
