# Generated by Django 3.1.2 on 2021-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0020_rename_project_display_name_to_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
