# Generated by Django 5.2.12 on 2026-03-17 14:55

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0020_alter_project_name_alter_project_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="Project ID can be found in the All Projects spreadsheet.",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[1-9][0-9]*$|^POS-20[0-9]{2}-[1-9][0-9]{3}$"),
                        "Enter a whole number or use the format POS-20YY-NNNN (for example, POS-2026-2001).",
                    )
                ],
                verbose_name="Project ID",
            ),
        ),
    ]
