# Generated by Django 4.0.6 on 2022-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0020_remove_permissions_mixin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullname",
            field=models.TextField(default=""),
        ),
    ]
