# Generated by Django 3.1.2 on 2021-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0021_convert_project_slug_to_slugfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
