# Generated by Django 5.2.12 on 2026-03-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0021_alter_project_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(
                help_text="This can be found in Section 7 of the NHSE OpenSAFELY Project Application form.",
                unique=True,
                verbose_name="Project title",
            ),
        ),
    ]
