# Generated by Django 5.0.1 on 2024-01-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobserver",
            "0021_copy_created_and_updated_fields_from_project_to_project_collaborations",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcollaboration",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collaborations",
                to="jobserver.org",
            ),
        ),
        migrations.AlterField(
            model_name="projectcollaboration",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collaborations",
                to="jobserver.project",
            ),
        ),
    ]
