# Generated by Django 4.1.7 on 2023-03-13 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0021_backfill_workspace_updated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("updated_at__isnull", False), ("updated_by__isnull", False)
                ),
                name="jobserver_workspace_both_updated_at_and_updated_by_set",
            ),
        ),
    ]
