# Generated by Django 4.0.6 on 2022-07-11 09:21

from django.db import migrations


def clear_fullname(apps, schema_editor):
    User = apps.get_model("jobserver", "User")

    for user in User.objects.exclude(fullname=""):
        first_name, *last_name = user.fullname.split(" ")

        user.first_name = first_name
        user.last_name = " ".join(last_name)
        user.fullname = ""
        user.save(update_fields=["first_name", "last_name", "fullname"])


def copy_first_and_last_name_to_fullname(apps, schema_editor):
    User = apps.get_model("jobserver", "User")

    for user in User.objects.all():
        user.fullname = f"{user.first_name} {user.last_name}".strip()
        user.save(update_fields=["fullname"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0021_add_user_fullname"),
    ]

    operations = [
        migrations.RunPython(
            copy_first_and_last_name_to_fullname,
            reverse_code=clear_fullname,
        )
    ]
