# Generated by Django 5.2.12 on 2026-03-18 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0022_alter_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="copilot",
            field=models.ForeignKey(
                help_text="Ask the BI Co-pilot Lead to find out who is Co-piloting this new project.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copiloted_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Co-pilot",
            ),
        ),
    ]
