# Generated by Django 3.1.2 on 2021-03-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0022_require_project_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="form_url",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_lead",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="project",
            name="data_access_legal_basis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="ethics_approval",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="evidence_of_scripting_languages",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="evidence_of_sharing_in_public",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="funding_source",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="has_signed_declaration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_research_on_cmo_priority_list",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="job_title",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="previous_experience_with_ehr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="requested_data_meets_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="satisfying_confidentiality",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="team_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="team_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="telephone",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="why_data_is_required",
            field=models.TextField(blank=True),
        ),
    ]
