# Generated by Django 4.1.7 on 2023-03-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0022_ensure_workspace_updated_fields_are_set"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="report",
            name="jobserver_report_both_published_at_and_published_by_set",
        ),
        migrations.RemoveField(
            model_name="report",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="report",
            name="published_by",
        ),
    ]
