# Generated by Django 5.0.1 on 2024-01-19 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0022_fix_projectcollaboration_project_and_org_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcollaboration",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="projectcollaboration",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_project_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectcollaboration",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="projectcollaboration",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_project_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
