# Generated by Django 4.0.6 on 2022-07-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0022_copy_first_and_last_name_to_fullname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
