# Generated by Django 3.1.2 on 2020-11-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0023_make_workspace_name_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="action_id",
            new_name="action",
        ),
    ]
