# Generated by Django 4.1.7 on 2023-03-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0023_remove_report_published_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("notifications_email", ""), _negated=True),
                fields=("notifications_email",),
                name="unique_notifications_email_ignore_empty",
            ),
        ),
    ]
