# Generated by Django 4.2.5 on 2023-09-26 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0023_require_projectcollaboration_created_and_updated_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditableEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old", models.TextField()),
                ("new", models.TextField()),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("project_member_added", "User added"),
                            ("project_member_removed", "User removed"),
                            ("project_member_updated_roles", "User's roles updated"),
                        ]
                    ),
                ),
                ("target_model", models.TextField()),
                ("target_field", models.TextField()),
                ("target_id", models.TextField()),
                ("target_user", models.TextField()),
                ("parent_model", models.TextField()),
                ("parent_id", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.TextField()),
            ],
        ),
    ]
