# Generated by Django 5.2.12 on 2026-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0023_alter_project_copilot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="orgs",
            field=models.ManyToManyField(
                help_text="This is the sponsoring organisation, found in Section 9 of the NHSE OpenSAFELY Project Application form.",
                related_name="projects",
                through="jobserver.ProjectCollaboration",
                to="jobserver.org",
                verbose_name="Link project to an organisation",
            ),
        ),
    ]
