# Generated by Django 5.0.1 on 2024-02-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0024_add_auditable_event_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="repo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces",
                to="jobserver.repo",
            ),
        ),
    ]
