# Generated by Django 4.0.6 on 2022-07-11 15:32

from django.db import migrations


def remove_empty_fullnames(apps, schema_editor):
    User = apps.get_model("jobserver", "User")

    User.objects.filter(fullname=" ").update(fullname="")


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0024_remove_labels_and_help_texts"),
    ]

    operations = [
        migrations.RunPython(
            remove_empty_fullnames,
            reverse_code=migrations.RunPython.noop,
        )
    ]
