# Generated by Django 3.1.2 on 2020-11-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0024_rename_action_id_to_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="selected_workspace",
        ),
    ]
