# Generated by Django 3.1.6 on 2021-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0024_add_researcher_registration_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="project_definition",
            field=models.TextField(default=""),
        ),
    ]
