# Generated by Django 4.1.7 on 2023-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobserver",
            "0024_ensure_user_notifications_email_is_unique_ignoring_empty_string",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_token",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_token_expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
