# Generated by Django 5.2.12 on 2026-03-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0024_alter_project_orgs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="copilot_support_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
