# Generated by Django 4.0.6 on 2022-07-14 06:57

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0025_fix_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(
                error_messages={"unique": "A user with that username already exists."},
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
    ]
