# Generated by Django 5.2.12 on 2026-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0025_alter_project_copilot_support_ends_at"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="project",
            name="unique_number_ignore_null",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("number",),
                name="unique_number_ignore_null",
                violation_error_message="Project with this Project ID already exists.",
            ),
        ),
    ]
