# Generated by Django 4.1.7 on 2023-05-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0025_user_login_token_user_login_token_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasefilepublishrequest",
            name="decision",
            field=models.TextField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")], null=True
            ),
        ),
        migrations.AddField(
            model_name="releasefilepublishrequest",
            name="decision_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="releasefilepublishrequest",
            name="decision_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_file_publish_requests_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportpublishrequest",
            name="decision_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="reportpublishrequest",
            name="decision_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_publish_requests_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportpublishrequest",
            name="decision",
            field=models.TextField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")], null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="releasefilepublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("decision__isnull", True),
                        ("decision_at__isnull", True),
                        ("decision_by__isnull", True),
                    ),
                    models.Q(
                        ("decision__isnull", False),
                        ("decision_at__isnull", False),
                        ("decision_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_releasefilepublishrequest_both_decision_at_decision_by_and_decision_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportpublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("decision__isnull", True),
                        ("decision_at__isnull", True),
                        ("decision_by__isnull", True),
                    ),
                    models.Q(
                        ("decision__isnull", False),
                        ("decision_at__isnull", False),
                        ("decision_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_reportpublishrequest_both_decision_at_decision_by_and_decision_set",
            ),
        ),
    ]
