# Generated by Django 5.0.2 on 2024-02-26 11:52

from django.db import migrations

import jobserver.models.job


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0026_add_custom_manager_to_JobRequest"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="job",
            managers=[
                ("objects", jobserver.models.job.JobManager()),
            ],
        ),
    ]
