# Generated by Django 3.1.2 on 2020-11-11 16:17

import base64
import secrets

from django.db import migrations


def new_id():
    """
    Return a random 16 character lowercase alphanumeric string
    We used to use UUID4's but they are unnecessarily long for our purposes
    (particularly the hex representation) and shorter IDs make debugging
    and inspecting the job-runner a bit more ergonomic.
    """
    return base64.b32encode(secrets.token_bytes(10)).decode("ascii").lower()


def set_identifiers(apps, schema_editor):
    JobRequest = apps.get_model("jobserver", "JobRequest")

    for job_request in JobRequest.objects.all():
        job_request.identifier = new_id()
        job_request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0026_add_job_request_identifier"),
    ]

    operations = [
        migrations.RunPython(set_identifiers, reverse_code=migrations.RunPython.noop)
    ]
