# Generated by Django 5.2.12 on 2026-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0027_alter_project_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(
                help_text="This can be found in Annex A - 1a of the NHSE Data Sharing Agreement.",
                unique=True,
                verbose_name="Project title",
            ),
        ),
    ]
