# Generated by Django 3.1.2 on 2020-11-11 16:21

from django.db import migrations, models

import jobserver.models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0027_set_job_request_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrequest",
            name="identifier",
            field=models.TextField(default=jobserver.models.new_id, unique=True),
        ),
    ]
