# Generated by Django 3.1.6 on 2021-04-08 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0027_add_membership_org_and_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="jobserver.project",
            ),
        ),
    ]
