# Generated by Django 4.0.6 on 2022-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0027_add_org_logo_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="logo_file",
            field=models.FileField(null=True, upload_to="org_logos/"),
        ),
    ]
