# Generated by Django 3.1.6 on 2021-04-08 13:54
from django.db import migrations


def add_datalab(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    Org.objects.create(name="DataLab", slug="datalab")


def remove_datalab(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")

    Org.objects.filter(slug="datalab").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0028_add_fk_between_project_and_workspace"),
    ]

    operations = [migrations.RunPython(add_datalab, reverse_code=remove_datalab)]
