# Generated by Django 3.1.2 on 2020-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0028_make_job_request_identifier_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="runner_status",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
