# Generated by Django 4.1.7 on 2023-05-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0028_remove_publish_requests_approved_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasefilepublishrequest",
            name="snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publish_requests",
                to="jobserver.snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="reportpublishrequest",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_requests",
                to="jobserver.report",
            ),
        ),
    ]
