# Generated by Django 5.2.13 on 2026-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0028_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="notification",
            field=models.TextField(
                choices=[
                    ("none", "None"),
                    ("per_job", "Per Job"),
                    ("per_request", "Per Request"),
                ],
                default="none",
            ),
        ),
    ]
