# Generated by Django 5.2.16 on 2026-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0029_alter_project_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.TextField(
                choices=[
                    ("internal", "Internal platform and data development"),
                    (
                        "legacy",
                        "Legacy COVID research activity predating specific approval processes",
                    ),
                    (
                        "legacy_approved",
                        "Legacy approved COVID research activity under the Job Server-managed approval process",
                    ),
                    (
                        "approved",
                        "Approved research activity under the 2025 or later Directions and the NHSE-managed approval process",
                    ),
                    ("unknown", "(Unknown category)"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
