# Generated by Django 3.1.2 on 2020-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0029_add_job_runner_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
