# Generated by Django 4.1.7 on 2023-04-10 09:38

from django.db import migrations
from django.db.models import F


def update_email_from_notification_email(apps, schema_editor):
    User = apps.get_model("jobserver", "User")

    # Update User.email with User.notifications_email if the user has a
    # notifications_email set.
    # In practice this should only be our two bot users (reports and interactive).
    User.objects.exclude(notifications_email="").update(email=F("notifications_email"))


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0029_convert_reportpublishrequest_report_to_an_fk"),
    ]

    operations = [
        migrations.RunPython(
            update_email_from_notification_email,
            reverse_code=migrations.RunPython.noop,
        )
    ]
