# Generated by Django 3.1.2 on 2020-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0030_add_job_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="identifier",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
