# Generated by Django 4.0.6 on 2022-07-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0030_use_isnull_for_check_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="jobrunner_state",
            field=models.JSONField(null=True),
        ),
    ]
