# Generated by Django 4.1.7 on 2023-05-05 10:08

from django.db import migrations


def copy_files_to_snapshots(apps, schema_editor):
    ReleaseFilePublishRequest = apps.get_model("jobserver", "ReleaseFilePublishRequest")
    Snapshot = apps.get_model("jobserver", "Snapshot")

    for publish_request in ReleaseFilePublishRequest.objects.filter(decision=None):
        snapshot = Snapshot.objects.create(
            created_by=publish_request.created_by,
            workspace=publish_request.workspace,
        )
        snapshot.files.add(*publish_request.files.all())

        publish_request.snapshot = snapshot
        publish_request.save(update_fields=["snapshot"])


def remove_snapshots(apps, schema_editor):
    Snapshot = apps.get_model("jobserver", "Snapshot")

    for snapshot in Snapshot.objects.filter(publish_requests__decision=None):
        no_decision = all(
            publish_request.decision is None
            for publish_request in snapshot.publish_requests.all()
        )

        # only delete if all publish requests have no decision
        if no_decision:
            snapshot.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0030_update_email_with_notifications_email"),
    ]

    operations = [
        migrations.RunPython(
            copy_files_to_snapshots,
            reverse_code=remove_snapshots,
        )
    ]
