# Generated by Django 3.2 on 2021-05-03 09:22

from django.db import migrations

import jobserver.authorization.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0030_add_project_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinvitation",
            name="roles",
            field=jobserver.authorization.fields.RolesField(default=list),
        ),
    ]
