# Generated by Django 5.2.16 on 2026-08-05 18:20

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0030_project_category"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="number_valid_format",
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.TextField(
                choices=[
                    ("internal", "Internal platform and data development"),
                    (
                        "legacy",
                        "Legacy COVID research activity predating specific approval processes",
                    ),
                    ("legacy_approved", "Legacy approved COVID research activity"),
                    ("approved", "Approved non-COVID research activity"),
                    ("unknown", "(Unknown category)"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="Project ID can be found in the All Projects spreadsheet. Enter a whole number or use the format POS-20YY-NNNN (for example, POS-2026-3001).",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^([1-9][0-9]*|POS-20[0-9]{2}-[1-9][0-9]{3})$"),
                        "Enter a whole number or use the format POS-20YY-NNNN (for example, POS-2026-3001).",
                    )
                ],
                verbose_name="Project ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("number__isnull", True),
                    ("number__regex", "^([1-9][0-9]*|POS-20[0-9]{2}-[1-9][0-9]{3})$"),
                    _connector="OR",
                ),
                name="number_valid_format",
            ),
        ),
    ]
