# Generated by Django 5.2.16 on 2026-08-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0030_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.TextField(
                choices=[
                    ("internal", "Internal platform and data development"),
                    (
                        "legacy",
                        "Legacy COVID research activity predating specific approval processes",
                    ),
                    ("legacy_approved", "Legacy approved COVID research activity"),
                    ("approved", "Approved non-COVID research activity"),
                    ("unknown", "(Unknown category)"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
