# Generated by Django 3.2 on 2021-05-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0031_add_project_invitation_roles_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmembership",
            name="created_by",
        ),
    ]
