# Generated by Django 4.0.6 on 2022-07-29 15:10
import json

from django.db import migrations


def convert_jobrunner_state_to_json(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    for backend in Backend.objects.exclude(jobrunner_state=None):
        if isinstance(backend.jobrunner_state, str):
            backend.jobrunner_state = json.loads(backend.jobrunner_state)
            backend.save(update_fields=["jobrunner_state"])


def convert_jobrunner_state_to_string(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    for backend in Backend.objects.exclude(jobrunner_state=None):
        if isinstance(backend.jobrunner_state, dict):
            backend.jobrunner_state = json.dumps(backend.jobrunner_state)
            backend.save(update_fields=["jobrunner_state"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0031_add_backend_jobrunner_state"),
    ]

    operations = [
        migrations.RunPython(
            convert_jobrunner_state_to_json,
            reverse_code=convert_jobrunner_state_to_string,
        )
    ]
