# Generated by Django 3.1.2 on 2020-12-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0031_add_job_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="workspace",
        ),
    ]
