# Generated by Django 4.1.7 on 2023-05-05 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0031_copy_releasefilepublishrequest_files_to_snapshots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releasefilepublishrequest",
            name="files",
        ),
    ]
