# Generated by Django 3.1.2 on 2020-12-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0032_remove_job_workspace_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="force_run",
        ),
    ]
