# Generated by Django 3.2 on 2021-05-03 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0032_remove_project_membership_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="researcherregistration",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
