# Generated by Django 4.1.7 on 2023-05-05 13:17

from django.db import migrations


def create_publish_requests_for_older_snapshots(apps, schema_editor):
    Snapshot = apps.get_model("jobserver", "Snapshot")

    for snapshot in Snapshot.objects.filter(publish_requests=None):
        decisions_kwargs = {}
        if snapshot.published_at:
            decisions_kwargs = {
                "decision_at": snapshot.published_at,
                "decision_by": snapshot.published_by,
                "decision": "approved",
            }

        snapshot.publish_requests.create(
            created_by=snapshot.created_by,
            workspace=snapshot.workspace,
            **decisions_kwargs,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0032_remove_releasefilepublishrequest_files"),
    ]

    operations = [
        migrations.RunPython(
            create_publish_requests_for_older_snapshots,
            # there's no simple path backwards for this one but leaving the
            # created objects around shouldn't cause issues
            reverse_code=migrations.RunPython.noop,
        )
    ]
