# Generated by Django 4.0.6 on 2022-08-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0032_fix_backend_jobrunner_state_format"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectInvitation",
        ),
    ]
