# Generated by Django 4.1.7 on 2023-05-05 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0033_add_publish_requests_for_snapshots_missing_them"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReleaseFilePublishRequest",
            new_name="SnapshotPublishRequest",
        ),
        migrations.RemoveConstraint(
            model_name="snapshotpublishrequest",
            name="jobserver_releasefilepublishrequest_both_created_at_and_created_by_set",
        ),
        migrations.AddConstraint(
            model_name="snapshotpublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_snapshotpublishrequest_both_created_at_and_created_by_set",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="snapshotpublishrequest",
            name="jobserver_releasefilepublishrequest_both_decision_at_decision_by_and_decision_set",
        ),
        migrations.AddConstraint(
            model_name="snapshotpublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("decision__isnull", True),
                        ("decision_at__isnull", True),
                        ("decision_by__isnull", True),
                    ),
                    models.Q(
                        ("decision__isnull", False),
                        ("decision_at__isnull", False),
                        ("decision_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_snapshotpublishrequest_both_decision_at_decision_by_and_decision_set",
            ),
        ),
        migrations.AlterField(
            model_name="reportpublishrequest",
            name="release_file_publish_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_publish_request",
                to="jobserver.snapshotpublishrequest",
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpublishrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshot_publish_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="snapshotpublishrequest",
            name="decision_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshot_publish_requests_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="reportpublishrequest",
            old_name="release_file_publish_request",
            new_name="snapshot_publish_request",
        ),
    ]
