# Generated by Django 3.1.2 on 2020-12-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0033_remove_job_force_run"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobOutput",
        ),
    ]
