# Generated by Django 3.2.1 on 2021-05-14 15:09

from django.db import migrations


def add_backends(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.create(name="nhsd", display_name="NHSD")
    Backend.objects.create(name="test", display_name="Test")
    Backend.objects.create(name="graphnet", display_name="Graphnet")


def remove_backends(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.delete(name="nhsd")
    Backend.objects.delete(name="test")
    Backend.objects.delete(name="graphnet")


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0033_add_various_created_ats"),
    ]

    operations = [migrations.RunPython(add_backends, reverse_code=remove_backends)]
