# Generated by Django 5.2.17 on 2026-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0033_remove_project_number_valid_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.TextField(
                choices=[
                    ("internal", "Internal platform and data development"),
                    (
                        "legacy",
                        "Legacy COVID research activity predating specific approval processes",
                    ),
                    ("legacy_approved", "Legacy approved COVID research activity"),
                    (
                        "approved",
                        "Approved research activity under the 2025 or later Directions and the NHSE-managed approval process",
                    ),
                    ("unknown", "(Unknown category)"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
