# Generated by Django 4.0.6 on 2022-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0034_require_workspace_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasefile",
            name="size",
            field=models.IntegerField(null=True),
        ),
    ]
