# Generated by Django 3.2.1 on 2021-05-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0034_add_more_backends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgmembership",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="jobserver.org",
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="jobserver.project",
            ),
        ),
    ]
