# Generated by Django 4.1.9 on 2023-05-18 06:18

from django.db import migrations


def switch_osi_report_creators_to_analysis_creator(apps, schema_editor):
    Report = apps.get_model("jobserver", "Report")

    for report in Report.objects.exclude(analysis_request=None):
        report.created_by = report.analysis_request.created_by
        report.save()


def switch_osi_report_creators_to_releaser(apps, schema_editor):
    Report = apps.get_model("jobserver", "Report")

    for report in Report.objects.exclude(analysis_request=None):
        report.created_by = report.release_file.created_by
        report.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobserver",
            "0035_remove_snapshot_published_fields",
        ),
    ]

    operations = [
        migrations.RunPython(
            switch_osi_report_creators_to_analysis_creator,
            reverse_code=switch_osi_report_creators_to_releaser,
        )
    ]
