# Generated by Django 3.1.2 on 2020-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0035_add_dummy_job_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="identifier",
            field=models.TextField(unique=True),
        ),
    ]
