# Generated by Django 3.2.1 on 2021-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0035_fix_org_and_project_membership_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="orgs",
            field=models.ManyToManyField(
                related_name="members",
                through="jobserver.OrgMembership",
                to="jobserver.Org",
            ),
        ),
    ]
