# Generated by Django 4.0.6 on 2022-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0036_backfill_releasefile_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasefile",
            name="size",
            field=models.IntegerField(),
        ),
    ]
