# Generated by Django 3.2.1 on 2021-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0036_add_org_users_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="github_orgs",
            field=models.JSONField(default=list),
        ),
    ]
