# Generated by Django 4.1.7 on 2023-04-10 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0036_switch_osi_report_creators_their_analysis_creator"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_notifications_email_ignore_empty",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notifications_email",
        ),
    ]
