# Generated by Django 4.1.7 on 2023-05-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobserver",
            "0037_remove_user_notifications_email",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshotpublishrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="snapshotpublishrequest",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshot_requests_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
