# Generated by Django 4.0.7 on 2022-08-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0037_make_releasefile_size_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasefile",
            name="mtime",
            field=models.DateTimeField(null=True),
        ),
    ]
