# Generated by Django 3.2.1 on 2021-05-27 10:17

from django.db import migrations


def add_opensafely_gh_org(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")
    Org.objects.update(github_orgs=["opensafely"])


def remove_opensafely_gh_org(apps, schema_editor):
    Org = apps.get_model("jobserver", "Org")
    Org.objects.update(github_orgs=[])


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0037_add_org_gh_orgs_field"),
    ]

    operations = [
        migrations.RunPython(
            add_opensafely_gh_org,
            reverse_code=remove_opensafely_gh_org,
        )
    ]
