# Generated by Django 3.1.2 on 2020-12-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0037_serialise_job_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="runner_status",
            new_name="status",
        ),
    ]
