# Generated by Django 4.1.7 on 2023-05-07 19:31

from django.db import migrations
from django.db.models import F


def copy_created_to_updated(apps, schema_editor):
    SnapshotPublishRequest = apps.get_model("jobserver", "SnapshotPublishRequest")

    SnapshotPublishRequest.objects.update(
        updated_at=F("created_at"), updated_by=F("created_by")
    )


def remove_updated(apps, schema_editor):
    SnapshotPublishRequest = apps.get_model("jobserver", "SnapshotPublishRequest")

    SnapshotPublishRequest.objects.update(updated_at=None, updated_by=None)


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0038_add_snapshotpublishrequest_updated_fields"),
    ]

    operations = [
        migrations.RunPython(copy_created_to_updated, reverse_code=remove_updated)
    ]
