# Generated by Django 4.0.7 on 2022-08-17 10:08


from django.db import migrations
from django.db.models import F


def copy_created_at_to_mtime(apps, schema_editor):
    ReleaseFile = apps.get_model("jobserver", "ReleaseFile")

    ReleaseFile.objects.update(mtime=F("created_at"))


def clear_mtime(apps, schema_editor):
    ReleaseFile = apps.get_model("jobserver", "ReleaseFile")

    ReleaseFile.objects.update(mtime=None)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0038_add_releasefile_mtime"),
    ]

    operations = [
        migrations.RunPython(copy_created_at_to_mtime, reverse_code=clear_mtime)
    ]
