# Generated by Django 3.1.2 on 2020-12-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0038_rename_job_runner_status_to_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="status_code",
        ),
    ]
