# Generated by Django 4.0.7 on 2022-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0039_backfill_releasefile_mtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasefile",
            name="mtime",
            field=models.DateTimeField(),
        ),
    ]
