# Generated by Django 3.1.2 on 2020-12-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0039_remove_job_status_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrequest",
            name="callback_url",
        ),
    ]
