# Generated by Django 4.1.7 on 2023-05-07 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0039_copy_snapshotpublishrequest_created_fields_to_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshotpublishrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="snapshotpublishrequest",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshot_requests_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="snapshotpublishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("updated_at__isnull", True), ("updated_by__isnull", True)
                    ),
                    models.Q(
                        ("updated_at__isnull", False), ("updated_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_snapshotpublishrequest_both_updated_at_and_updated_by_set",
            ),
        ),
    ]
