# Generated by Django 4.1.7 on 2023-05-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0040_require_snapshotpublishrequest_updated_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportPublishRequest",
        ),
        migrations.RenameModel(
            old_name="SnapshotPublishRequest",
            new_name="PublishRequest",
        ),
        migrations.RemoveConstraint(
            model_name="publishrequest",
            name="jobserver_snapshotpublishrequest_both_created_at_and_created_by_set",
        ),
        migrations.RemoveConstraint(
            model_name="publishrequest",
            name="jobserver_snapshotpublishrequest_both_decision_at_decision_by_and_decision_set",
        ),
        migrations.RemoveConstraint(
            model_name="publishrequest",
            name="jobserver_snapshotpublishrequest_both_updated_at_and_updated_by_set",
        ),
        migrations.AddConstraint(
            model_name="publishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("created_at__isnull", True), ("created_by__isnull", True)
                    ),
                    models.Q(
                        ("created_at__isnull", False), ("created_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_publishrequest_both_created_at_and_created_by_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="publishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("decision__isnull", True),
                        ("decision_at__isnull", True),
                        ("decision_by__isnull", True),
                    ),
                    models.Q(
                        ("decision__isnull", False),
                        ("decision_at__isnull", False),
                        ("decision_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="jobserver_publishrequest_both_decision_at_decision_by_and_decision_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="publishrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("updated_at__isnull", True), ("updated_by__isnull", True)
                    ),
                    models.Q(
                        ("updated_at__isnull", False), ("updated_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="jobserver_publishrequest_both_updated_at_and_updated_by_set",
            ),
        ),
        migrations.AddField(
            model_name="publishrequest",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publish_requests",
                to="jobserver.report",
            ),
        ),
        migrations.AlterField(
            model_name="publishrequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publishrequest",
            name="decision_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publish_requests_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
