# Generated by Django 3.1.2 on 2020-12-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0040_remove_callback_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="started",
        ),
    ]
