# Generated by Django 4.0.7 on 2022-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0040_set_releasefile_mtime_to_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasefile",
            name="uploaded_at",
            field=models.DateTimeField(null=True),
        ),
    ]
