# Generated by Django 3.2.4 on 2021-06-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0041_add_user_backends_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
