# Generated by Django 4.1.9 on 2023-06-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0041_merge_publish_request_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishrequest",
            name="snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_requests",
                to="jobserver.snapshot",
            ),
        ),
    ]
