# Generated by Django 4.0.7 on 2022-08-16 14:12

from django.db import migrations
from django.db.models import F


def copy_created_at_to_uploaded_at(apps, schema_editor):
    ReleaseFile = apps.get_model("jobserver", "ReleaseFile")

    ReleaseFile.objects.update(uploaded_at=F("created_at"))


def set_uploaded_at_to_none(apps, schema_editor):
    ReleaseFile = apps.get_model("jobserver", "ReleaseFile")

    ReleaseFile.objects.update(uploaded_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0041_add_releasefile_uploaded_at"),
    ]

    operations = [
        migrations.RunPython(
            copy_created_at_to_uploaded_at,
            reverse_code=set_uploaded_at_to_none,
        )
    ]
