# Generated by Django 4.1.9 on 2023-06-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0042_delete_publish_requests_when_snapshots_are_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishrequest",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_requests",
                to="jobserver.snapshot",
            ),
        ),
    ]
