# Generated by Django 4.0.7 on 2022-08-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0042_backfill_releasefile_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseFileReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")]
                    ),
                ),
                ("comments", models.JSONField()),
                ("created_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_file_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="jobserver.releasefile",
                    ),
                ),
            ],
        ),
    ]
