# Generated by Django 3.1.2 on 2020-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0042_remove_job_needed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="db",
            field=models.TextField(
                choices=[
                    ("slice", "Cut-down (but real) database"),
                    ("full", "Full database"),
                ]
            ),
        ),
    ]
