# Generated by Django 3.1.2 on 2020-12-21 11:52

from django.db import migrations


def delete_jobrequestless_jobs(apps, schema_editor):
    Job = apps.get_model("jobserver", "Job")

    Job.objects.filter(job_request=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0043_remove_workspace_db_dummy_option"),
    ]

    operations = [
        migrations.RunPython(
            delete_jobrequestless_jobs, reverse_code=migrations.RunPython.noop
        )
    ]
