# Generated by Django 3.2.5 on 2021-10-18 09:11

from django.db import migrations, models

import jobserver.authorization.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0043_enforce_publish_requests_have_a_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="roles2",
            field=jobserver.authorization.fields.RolesArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="roles2",
            field=jobserver.authorization.fields.RolesArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles2",
            field=jobserver.authorization.fields.RolesArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
