# Generated by Django 4.0.7 on 2022-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0043_add_release_file_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="review",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="releasefile",
            name="metadata",
            field=models.JSONField(null=True),
        ),
    ]
