# Generated by Django 3.2.1 on 2021-06-11 08:09

from django.db import migrations


def fix_name(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    obj = Backend.objects.get(name="nhsd")
    obj.name = "databricks"
    obj.display_name = "databricks"
    obj.save()


def unfix_name(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    obj = Backend.objects.get(name="databricks")
    obj.name = "nhsd"
    obj.display_name = "NHSD"
    obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0043_set_backend_active_states"),
    ]

    operations = [migrations.RunPython(fix_name, reverse_code=unfix_name)]
