# Generated by Django 3.1.2 on 2020-12-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0044_delete_job_requestless_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="jobserver.jobrequest",
            ),
        ),
    ]
