# Generated by Django 4.0.7 on 2022-09-21 13:16

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0045_use_django_json_encode_for_release_requested_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="repo_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces",
                to="jobserver.repo",
            ),
        ),
    ]
