# Generated by Django 3.2.5 on 2021-10-18 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0045_copy_roles_to_roles2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgmembership",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="projectmembership",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
    ]
