# Generated by Django 3.1.2 on 2020-12-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0045_make_job_request_required_on_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="jobserver.jobrequest",
            ),
        ),
    ]
