# Generated by Django 3.1.2 on 2020-12-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0046_protect_against_cascading_job_deletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("display_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
