# Generated by Django 4.0.7 on 2022-09-21 13:17

from django.db import migrations


def copy_repo_url_to_fks(apps, schema_editor):
    Repo = apps.get_model("jobserver", "Repo")
    Workspace = apps.get_model("jobserver", "Workspace")

    for workspace in Workspace.objects.all():
        repo, _ = Repo.objects.get_or_create(url=workspace.repo)
        workspace.repo_fk = repo
        workspace.save()


def remove_repo_fks(apps, schema_editor):
    Workspace = apps.get_model("jobserver", "Workspace")

    Workspace.objects.update(repo_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0046_add_repo_model"),
    ]

    operations = [
        migrations.RunPython(
            copy_repo_url_to_fks,
            reverse_code=remove_repo_fks,
        )
    ]
