# Generated by Django 3.2.5 on 2021-10-18 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0046_remove_roles_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orgmembership",
            old_name="roles2",
            new_name="roles",
        ),
        migrations.RenameField(
            model_name="projectmembership",
            old_name="roles2",
            new_name="roles",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="roles2",
            new_name="roles",
        ),
    ]
