# Generated by Django 3.2.4 on 2021-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0047_add_org_description_and_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="db",
            field=models.TextField(choices=[("full", "Full database")]),
        ),
    ]
