# Generated by Django 4.0.7 on 2022-09-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0047_copy_repo_urls_to_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="repo",
        ),
    ]
