# Generated by Django 3.1.2 on 2020-12-07 11:42

from django.db import migrations


BACKENDS = [
    "EMIS",
    "Expectations",
    "TPP",
]


def add_backends(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.bulk_create(
        Backend(name=b.lower(), display_name=b) for b in BACKENDS
    )


def remove_backends(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0047_add_backend"),
    ]

    operations = [migrations.RunPython(add_backends, reverse_code=remove_backends)]
