# Generated by Django 3.2.4 on 2021-06-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0048_remove_slice_db_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces",
                to="jobserver.project",
            ),
        ),
    ]
