# Generated by Django 3.1.2 on 2020-12-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0048_add_backends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobrequest",
            old_name="backend",
            new_name="backend_old",
        ),
    ]
