# Generated by Django 4.0.7 on 2022-09-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0048_remove_workspace_repo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="repo_fk",
            new_name="repo",
        ),
    ]
