# Generated by Django 3.2.4 on 2021-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0049_require_workspaces_have_a_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="db",
            field=models.TextField(choices=[("full", "Full database")], default="full"),
        ),
    ]
