# Generated by Django 4.0.6 on 2022-08-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0049_rename_workspace_repo_fk_to_repo"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="signed_off_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="signed_off_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces_signed_off",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
