# Generated by Django 3.2.4 on 2021-06-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0050_set_full_as_default_on_workspace_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backendmembership",
            name="backend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="jobserver.backend",
            ),
        ),
    ]
