# Generated by Django 3.2.4 on 2021-06-29 16:01

from django.db import migrations

import jobserver.models.core


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0051_rename_backend_members_to_memberships"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", jobserver.models.core.UserManager()),
            ],
        ),
    ]
