# Generated by Django 4.1 on 2022-09-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0051_add_repo_signed_off_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="has_sign_offs_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
