# Generated by Django 3.1.2 on 2020-12-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0051_link_jobrequests_to_backends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrequest",
            name="backend_old",
        ),
    ]
