# Generated by Django 3.1.2 on 2020-12-21 16:00

from django.db import migrations, models

import jobserver.models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0052_remove_jobrequest_backend_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="auth_token",
            field=models.TextField(default=jobserver.models.generate_token),
        ),
    ]
