# Generated by Django 4.1 on 2022-09-28 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0052_add_repo_has_sign_offs_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="internal_signed_off_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="internal_signed_off_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internally_signed_off_repos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
