# Generated by Django 3.1.2 on 2020-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0053_add_backend_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
