# Generated by Django 3.1.2 on 2020-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0053_add_backend_auth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
