# Generated by Django 3.2.4 on 2021-07-14 16:07

from django.db import migrations, models

import jobserver.models.outputs


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0055_add_publicrelease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="id",
            field=models.CharField(
                default=jobserver.models.outputs.new_ulid_str,
                editable=False,
                max_length=26,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="releasefile",
            name="id",
            field=models.CharField(
                default=jobserver.models.outputs.new_ulid_str,
                editable=False,
                max_length=26,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
