# Generated by Django 4.1 on 2022-10-18 09:03

from django.db import migrations
from django.db.models import F


def clear_updated_fields(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.update(updated_by=None)


def set_updated_fields(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.update(updated_at=F("created_at"), updated_by=F("created_by"))


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0055_add_project_updated_fields"),
    ]

    operations = [
        migrations.RunPython(
            set_updated_fields,
            reverse_code=clear_updated_fields,
        )
    ]
