# Generated by Django 4.1 on 2022-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0056_set_project_updated_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.TextField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("postponed", "Postponed"),
                    ("retired", "Retired"),
                ],
                default="ongoing",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status_description",
            field=models.TextField(default="", blank=True),
        ),
    ]
