# Generated by Django 4.1.2 on 2022-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0057_add_project_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="purpose",
            field=models.TextField(default=""),
        ),
    ]
