# Generated by Django 3.2.5 on 2021-07-22 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0057_rename_public_release_to_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="published_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
