# Generated by Django 3.1.2 on 2021-01-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0058_set_all_stats_to_tpp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="backend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stats",
                to="jobserver.backend",
            ),
        ),
    ]
