# Generated by Django 3.2.5 on 2021-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0058_add_snapshot_published_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="level_4_url",
            field=models.TextField(default=""),
        ),
    ]
