# Generated by Django 4.1.2 on 2022-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0058_add_workspace_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="has_github_outputs",
            field=models.BooleanField(default=False),
        ),
    ]
