# Generated by Django 3.1.2 on 2021-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0059_make_stats_backend_not_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="stats",
            unique_together={("backend", "url")},
        ),
    ]
