# Generated by Django 4.1.2 on 2022-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0059_add_repo_has_github_outputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="copilot_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
