# Generated by Django 3.1.2 on 2021-01-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0060_add_stats_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_email",
            field=models.TextField(default=""),
        ),
    ]
