# Generated by Django 3.2.5 on 2021-08-03 11:07

from django.db import migrations


def set_existing_projects_to_old_process(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.update(uses_new_release_flow=False)


def set_existing_projects_to_new_process(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.update(uses_new_release_flow=True)


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0061_add_project_uses_new_release_flow"),
    ]

    operations = [
        migrations.RunPython(
            set_existing_projects_to_old_process,
            reverse_code=set_existing_projects_to_new_process,
        )
    ]
