# Generated by Django 4.1.2 on 2022-12-09 09:44

from django.db import migrations


def switch_completed_for_completed_awaiting(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.filter(status="completed").update(status="completed-awaiting")


def switch_completed_awaiting_for_completed(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.filter(status="completed-awaiting").update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0062_add_extra_project_statuses"),
    ]

    operations = [
        migrations.RunPython(
            switch_completed_for_completed_awaiting,
            reverse_code=switch_completed_awaiting_for_completed,
        )
    ]
