# Generated by Django 3.1.2 on 2021-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0062_copy_email_to_notifications_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="will_notify",
            field=models.BooleanField(default=False),
        ),
    ]
