# Generated by Django 3.2.5 on 2021-08-06 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0062_set_existing_projects_to_old_release_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasefile",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="releasefile",
            name="deleted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="releasefile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deleted_at", None), ("deleted_by", None)),
                    models.Q(("deleted_at", None), ("deleted_by", None), _negated=True),
                    _connector="OR",
                ),
                name="jobserver_releasefile_deleted_fields_both_set",
            ),
        ),
    ]
