# Generated by Django 3.2.5 on 2021-08-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0063_add_release_file_deleted_at_and_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backend",
            old_name="name",
            new_name="slug",
        ),
    ]
