# Generated by Django 4.1.2 on 2022-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0063_switch_project_status_completed_for_completed_awaiting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.TextField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("postponed", "Postponed"),
                    ("retired", "Retired"),
                    ("ongoing-and-linked", "Ongoing - paper/report linked"),
                    ("completed-and-linked", "Completed - paper/report linked"),
                    ("completed-and-awaiting", "Completed - awaiting paper/report"),
                ],
                default="ongoing",
            ),
        ),
    ]
