# Generated by Django 3.2.5 on 2021-08-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0064_rename_backend_name_to_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backend",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
