# Generated by Django 4.1.2 on 2022-12-13 08:30

from django.db import migrations


def rename_opensafely_testing_to_opensafely_internal(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.filter(slug="opensafely-testing").update(
        slug="opensafely-internal", name="OpenSAFELY Internal"
    )


def rename_opensafely_internal_to_opensafely_testing(apps, schema_editor):
    Project = apps.get_model("jobserver", "Project")

    Project.objects.filter(slug="opensafely-internal").update(
        slug="opensafely-testing", name="OpenSAFELY Testing"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0064_remove_bare_project_completed_status"),
    ]

    operations = [
        migrations.RunPython(
            rename_opensafely_testing_to_opensafely_internal,
            reverse_code=rename_opensafely_internal_to_opensafely_testing,
        )
    ]
