# Generated by Django 3.1.2 on 2021-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0064_add_job_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="backend",
            name="parent_directory",
            field=models.TextField(default=""),
        ),
    ]
