# Generated by Django 3.2.5 on 2021-08-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0065_alter_backend_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backend",
            old_name="display_name",
            new_name="name",
        ),
    ]
