# Generated by Django 3.1.2 on 2021-01-29 10:31

from django.db import migrations


def set_tpp_parent_dir(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.filter(name="tpp").update(
        parent_directory="/d/Level4Files/workspaces"
    )


def unset_tpp_parent_dir(apps, schema_editor):
    Backend = apps.get_model("jobserver", "Backend")

    Backend.objects.filter(name="tpp").update(parent_directory="")


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0065_add_backend_parent_dir"),
    ]

    operations = [
        migrations.RunPython(set_tpp_parent_dir, reverse_code=unset_tpp_parent_dir)
    ]
