# Generated by Django 3.2.5 on 2021-09-20 09:37

from django.db import migrations, models

import jobserver.models.core


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0066_rename_display_name_backend_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="github_orgs",
            field=models.JSONField(default=jobserver.models.core.default_github_orgs),
        ),
    ]
