# Generated by Django 3.2.5 on 2021-10-15 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobserver", "0069_add_created_by_to_org_and_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
