# Generated by Django 5.0.8 on 2024-08-22 08:18

from django.db import migrations


def fun(apps, schema_editor):
    assert False


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0001_squashed_2024_06"),
    ]

    operations = [migrations.RunPython(fun)]
