upload_release_file = "upload_release_file"
view_release_file = "view_release_file"


backend_manage = "backend_manage"
job_cancel = "job_cancel"
job_run = "job_run"
org_create = "org_create"
org_invite_members = "org_invite_members"
project_invite_members = "project_invite_members"
project_membership_edit = "project_membership_edit"
project_review = "project_review"
release_file_delete = "release_file_delete"
snapshot_create = "snapshot_create"
snapshot_publish = "snapshot_publish"
user_manage = "user_manage"
workspace_archive = "workspace_archive"
workspace_create = "workspace_create"
workspace_toggle_notifications = "workspace_toggle_notifications"
