create_org = "create_org"
create_snapshot = "create_snapshot"
delete_release_file = "delete_release_file"
invite_org_members = "invite_org_members"
invite_project_members = "invite_project_members"
manage_backends = "manage_backends"
manage_project_members = "manage_project_members"
manage_project_workspaces = "manage_project_workspaces"
manage_users = "manage_users"
publish_snapshot = "publish_snapshot"
review_project = "review_project"
run_job = "run_job"
toggle_workspace_notifications = "toggle_workspace_notifications"
upload_release_file = "upload_release_file"
view_release_file = "view_release_file"


job_cancel = "job_cancel"
workspace_archive = "workspace_archive"
