# Generated by Django 4.1.10 on 2023-07-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="old_url",
            field=models.TextField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.CheckConstraint(
                check=models.Q(("old_url", ""), _negated=True),
                name="old_url_is_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("old_url__endswith", "/"), ("old_url__startswith", "/")
                ),
                name="old_url_endswith_and_startswith_slash",
            ),
        ),
    ]
