# Generated by Django 4.0.6 on 2022-07-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0001_add_redirect"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="redirect",
            name="redirects_redirect_only_one_target_model_set",
        ),
        migrations.AddField(
            model_name="redirect",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redirects",
                to="jobserver.org",
            ),
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("org__isnull", False),
                        ("project__isnull", True),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("org__isnull", True),
                        ("project__isnull", False),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("org__isnull", True),
                        ("project__isnull", True),
                        ("workspace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="redirects_redirect_only_one_target_model_set",
            ),
        ),
    ]
