# Generated by Django 4.1.2 on 2023-01-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0001_initial"),
        ("redirects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="redirect",
            name="redirects_redirect_only_one_target_model_set",
        ),
        migrations.AddField(
            model_name="redirect",
            name="analysis_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redirects",
                to="interactive.analysisrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("analysis_request__isnull", False),
                        ("org__isnull", True),
                        ("project__isnull", True),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("analysis_request__isnull", True),
                        ("org__isnull", False),
                        ("project__isnull", True),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("analysis_request__isnull", True),
                        ("org__isnull", True),
                        ("project__isnull", False),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("analysis_request__isnull", True),
                        ("org__isnull", True),
                        ("project__isnull", True),
                        ("workspace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="redirects_redirect_only_one_target_model_set",
            ),
        ),
    ]
