# Generated by Django 5.1.6 on 2025-03-13 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobserver", "0011_sitealert"),
        ("redirects", "0002_ensure_old_url_has_leading_and_trailing_slashes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="redirect",
            name="redirects_redirect_only_one_target_model_set",
        ),
        migrations.RemoveField(
            model_name="redirect",
            name="analysis_request",
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("org__isnull", False),
                        ("project__isnull", True),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("org__isnull", True),
                        ("project__isnull", False),
                        ("workspace__isnull", True),
                    ),
                    models.Q(
                        ("org__isnull", True),
                        ("project__isnull", True),
                        ("workspace__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="redirects_redirect_only_one_target_model_set",
            ),
        ),
    ]
