# Generated by Django 4.0.6 on 2022-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0002_add_redirect_org_fk"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="redirect",
            name="redirects_redirect_both_deleted_at_and_deleted_by_set",
        ),
        migrations.AddConstraint(
            model_name="redirect",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("deleted_at__isnull", True), ("deleted_by__isnull", True)
                    ),
                    models.Q(
                        ("deleted_at__isnull", False), ("deleted_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="redirects_redirect_both_deleted_at_and_deleted_by_set",
            ),
        ),
    ]
