---
name: Test and build Docker image

on:
  merge_group:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Python formatting check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
        with:
          python-version: "3.12"
          install-just: true
          install-uv: true
          cache: uv
      - name: Check formatting, linting, and import sorting
        run: just check

  test:
    name: Python & JS tests
    runs-on: ubuntu-24.04
    needs: check

    services:
      postgres:
        # When this updates, you need to also update:
        # - docker/docker-compose.yaml:9
        # - tests/test_repository.py:30
        # to match this SHA
        image: postgres:17@sha256:5c855ad7b85e68e48a62f34662853f38b57c1c1d80f3a927ab58034fd6d31c5e # v17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: jobserver
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
        with:
          python-version: "3.12"
          install-just: true
          install-uv: true
          cache: uv

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install node_modules
        run: just assets-install --ignore-scripts

      - name: Lint assets
        run: npm run lint:ci

      - name: Run JS tests
        run: just assets-test

      - name: Build assets
        run: just assets-build

      - name: Install venv
        run: just devenv

      - name: Run tests
        env:
          DATABASE_URL: postgres://user:password@localhost/jobserver
          GITHUB_TOKEN: empty
          GITHUB_TOKEN_TESTING: ${{ secrets.OPENSAFELY_GITHUB_TESTING_ORG_PAT }}
          SECRET_KEY: 12345
          SOCIAL_AUTH_GITHUB_KEY: test
          SOCIAL_AUTH_GITHUB_SECRET: test
        run: |
          just check-migrations
          # hardcode n because auto=2 in CI for some reason
          just test-ci -n 4

      - name: Upload HTML coverage report if tests failed
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-coverage-report
          path: htmlcov
          # don't fail the job because no files were found, we expect this when
          #  * the tests passed with 100% coverage
          #  * a test failed and coverage didn't run
          if-no-files-found: ignore
        if: ${{ failure() }}  # only upload when the previous step, run tests, fails

  test-functional:
    name: Docker functional tests
    runs-on: ubuntu-24.04
    needs:
      - check
      - lint-dockerfile

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
        with:
          install-just: true

      - name: Build docker image and run functional tests in it
        run: |
          # build docker and run test
          just docker-test-functional

  lint-dockerfile:
    name: Dockerfile lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: docker/Dockerfile

  docker-test:
    name: Docker unit & smoke tests
    runs-on: ubuntu-24.04
    needs:
      - check
      - lint-dockerfile

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
        with:
          install-just: true

      - name: Build docker image for both prod and dev
        run: |
            just docker-build prod
            just docker-build dev

      - name: Run unit tests on docker dev image
        env:
          GITHUB_TOKEN_TESTING: ${{ secrets.OPENSAFELY_GITHUB_TESTING_ORG_PAT }}
        run: |
          # build docker and run test
          just docker-test-py -n 4  # hardcode n because auto does not dtrt in docker

      - name: Run smoke test on prod
        run: |
          just docker-serve prod -d
          sleep 5
          just docker-smoke-test || { docker logs job-server-prod-1; exit 1; }

      - name: Save docker image
        run: |
          docker save job-server | zstd --fast -o /tmp/job-server.tar.zst

      - name: Upload docker image
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
            name: job-server-image
            path: /tmp/job-server.tar.zst
            compression-level: 0
