name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 23 * * SUN"

jobs:
  update-dependencies:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.12"
        install-just: true

    - uses: actions/create-github-app-token@v2
      id: generate-token
      with:
        app-id: 1031449  # opensafely-core Create PR app
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}

    - uses: bennettoxford/update-dependencies-action@v1
      with:
        token: ${{ steps.generate-token.outputs.token }}
        update_command: |
          just upgrade-pipeline
          just update-dependencies
