---
name: Check uvmirror

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  check-uvmirror:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@5b3030fbbcf069c94e352b4f0a94100fae4dbd82 # v1.6.1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Ensure requirements.uvmirror.txt is consistent with uv.lock
        run: just uvmirror && git diff -s --exit-code
