---
name: Check uvmirror

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  check-uvmirror:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@5b3030fbbcf069c94e352b4f0a94100fae4dbd82 # v1.6.1
        with:
          install-just: true
          install-uv: true

      - name: Ensure requirements.uvmirror.txt is consistent with uv.lock
        run: just uvmirror && git diff -s --exit-code
